CREATE INDEX IDX_ORDER ON ORDER1
(Ino, Odate);

CREATE INDEX IDX_CUSTOMER ON CUSTOMER
(Age, Sex);

CREATE INDEX IDX_RETAILER ON RETAILER
(Address);

CREATE INDEX IDX_CATEGORY ON CATEGORY
(Large_category);

CREATE INDEX IDX_ITEM ON ITEM
(Iname);

CREATE INDEX IDX_SHOPPINGBAG ON SHOPPINGBAG
(Inum, Bquantity);

CREATE INDEX IDX_STOCK ON STOCK
(Squantity, Inum, Rnum);

CREATE INDEX IDX_PRODUCERLOCATION ON PRODUCERLOCATION
(Importer, Producer);
